---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: ubuntu-vault-virtualbox
    driver:
      box: ubuntu-vault-virtualbox-test
      box_url: file:///<%= ENV['PWD'] %>/output-vagrant-ubuntu-vault/package.box
      provider: virtualbox

verifier:
  name: inspec
  sudo: false

suites:
  - name: default